### ISSUE TITLE
Link docker hub and github repos?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-images#2]
This was an old request from Trey, posting here. Not sure how relevant:

>Would you be able to link the docker hub and github repos together?  I can’t tell how or if it’s possible.  When I go to create an automated build I can only choose from my treydock repos.
> 
>- Trey

 https://hub.docker.com/u/ohiosupercomputer/dashboard/teams/?team=owners

But the docker image is at https://hub.docker.com/r/treydock/ood/ from original https://github.com/treydock/ood-images even though we forked this to https://github.com/OSC/ood-images

**Comment by treydock** [comment]
I setup automated builds a while ago but it sometimes doesn't trigger so always just been building locally and pushing the containers to docker hub.

**Comment by alansill** [comment]
Are the OOD docker images being maintained as part of or in syunc with the installation options? We would strongly prefer installing and maintaining OOD as a set of containers for the various services, rather than install on bare metal. This would ideally allow scaling and redundancy of the OOD services, and improve the ability to deploy OOD on managed datacenter infrastructure settings.

**Comment by johrstrom** [comment]
They are maintained with major versions, but they're not meant to be for production use.  They're proof of concept and development tools. 

I'm not sure what this issue was about, but we do have https://hub.docker.com/u/ohiosupercomputer organization so I'm closing this ticket.

@alansill that's not to stop this conversation though, maybe we can open a new ticket or discuss more on discourse (we have https://discourse.osc.edu/t/ood-container-working-off-of-discussion-started-on-todays-webinar/466), but I'd like very much to provide production ready containers and I 100% agree with you, we're just not there yet. 

I started to write my answer to you, but, I'll take my own advice and move the conversation to discourse.
