### ISSUE TITLE
Combine with ood-images-full

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-images#3]
There's a little bit of confusion with the ood-images-full repository and I've been working on images this morning, though in the buildah/podman stack. 

My proposal is this: to combine all logical "imaging" scripts/workflows/files into this repo.  

The initial directory structure would have at least these 4 sub directories.  I can start by committing my podman work in it's own directory, leaving everything else alone. 
```
vagrant/...
docker/...
packer/...
podman/...
```

This proposal ticket is then to agree on the idea, then note any pain points the migration may have, like some CI/CD workflow depending on file X to be at the top level directory (or even in the other repo)

@treydock @ericfranz @MorganRodgers FYC

**Comment by treydock** [comment]
I don't know how others have used the two repos but this repo, `ood-images` only gets updates during each major release of OnDemand as it's a way for someone to get a working copy of OnDemand installed via either Docker or VMware.  The purpose of `ood-images-full` is to get full OnDemand environment working that includes batch scheduler.  If we did merge we'd have to be conscious that some subdirectories are for releases and some are for development.  Also some of the scripts in this repo are shared by all the deployment methods. I'm not opposed to the idea but right now the two repos likely have two very different purposes.

**Comment by ericfranz** [comment]
If we merge into one repo I would suggest a different directory structure instead of by technology:

```
prod_simple/ # everything currently in this repo
dev_slurm/ # ood-images-full
dev_pbspro/
```

In other words, grouped by what you end up with (OnDemand or OnDemand+Slurm etc). So if the new podman includes Slurm then that would go under the dev_slurm.

But maybe we should have a separate repo for the dev images. We could start by keeping ood-images-full and maybe better naming it? (ood-images-dev) and moving those files into a subdir and then add the images for the other resource managers that we have on Morgan’s laptop or other locations

Consolidation of the batch connect repos (when proxy improvements and/or a new batch connect plugin support it) and consolidation of the core app repos into OSC/ondemand  will be bigger wins.

**Comment by ericfranz** [comment]
A better suggestion for the die names than the one I gave above might be

```
ondemand/
dev/ondemand_with_slurm/
dev/ondemand_with_pbspro/
```

Or if ood-images-full is renamed ood-images-dev then that repo gets:

```
ondemand_with_slurm
ondemand_with_pbspro
```

**Comment by johrstrom** [comment]
>  the two repos likely have two very different purposes.

Yea my reasoning for this was the idea that they're *not* really that different. The whole premise of this ticket was - "well all this stuff is developer tooling (whether you wanted the full stack or just an OOD instance), so why not just combine it all". 

Directory structure aside - I think we'd need to at least confirm it's a worthwhile endeavour to begin with.

**Comment by treydock** [comment]
Unless it's used differently than intended, this repo was for production releases of OnDemand to give other's ability to quickly play around with OnDemand, not intended to make development easy.  It's the ood-images-full that was designed for development. This repo also predates the RPM releases so providing a VMware image of an install that has like 3 steps just doesn't seem that useful to me anymore. If someone uses the vmware image it will take them longer to customize the operating system to their environment than to just add OnDemand to one of their systems. The ood-images-full repo seems more useful to me as that one is a full stack that works with very little effort. This repo isn't useful by itself.

Maybe we need to reach out to community and find out if people are using the repos and ask how they are using them? Maybe how I intended them to be used it not how they are actually getting used.

**Comment by johrstrom** [comment]
> Maybe we need to reach out to community 

I can open a post on discourse, though I don't know how much activity it'll get. What other methods do you think we could do? 

> ability to quickly play around with OnDemand, not intended to make development easy

I feel like these are the same goals - Make things super easy for someone to get started and play around with it. If they're developer, it (whatever *it* is, container/vagrant image/etc) all that stuff is enabled.

**Comment by treydock** [comment]
They are sort of the same goals but the ood-images-full actually has batch environment and can be run on desktop or laptop.  The ood-images lacks batch environment and the vmware image requires infrastructure be in place to actually use the image unless someone pays to use like vmware fusion on their personal computer.

If the repos are unified maybe the directories describe environment and backing implementation like "dev-vagrant" and "deploy-vmware".  I'm not great with names so hopefully get the idea.  Maybe all that's needed is some name and a README describing what each one does and how to use it. For docker "dev" and "deploy" could have same setup scripts but dev have helper script to launch container using /sbin/init and then another one to actually log into that container.

**Comment by ericfranz** [comment]
That's another thing, this ood-images wasn't really targeting development, and ood-images-full includes batch environment. The podman addition doesn't include batch environment but is targeting development, so it doesn't really fit in either as it stands - which is why turning one of these (or adding a new repo and deprecating one of these) into a dev focused, which can have multiple images in separate directories targeting different environment types (ondemand, ondemand+slurmbatch, ondemand+lsfbatch, etc.) seems appropriate. These could also be separate repos and we could just collocate them all with naming convention like we have now with ood-images and ood-images-full. FWIW There is also https://github.com/vsoch/ood-compose  which targets interactive app development, and I think has some of the same goals as the podman addition.

Besides the ability to update all of the images in one commit for the latest version of OnDemand, or sharing some scripts/information across all images, are there any other benefits to merging any of these repos? The drawbacks are of course is typically you will only want to use one specific image and you can't clone just that image's directory to the desired location. I'm not sure how having images in sub-directories of a repo would affect integration with DockerHub or SingularityHub.

**Comment by treydock** [comment]
There are some scripts we could share between various builds.  I don't think subdirectories matter for docker or singularity as you typically `cd` to desired directory to do something like `docker build` and then push the image and that part doesn't care about directory location. For singularity it also wouldn't matter I don't think.

I'd be in favor of one repo with a good README to keep everything in one place and avoid confusion about which repo to clone.  Maybe main README just describes each directory then README for each directory goes into greater detail about usage. Could link to those subdirectory READMEs from main repo one.

**Comment by johrstrom** [comment]
> are there any other benefits to merging any of these repos?

Simplicity; everything is here to get you started or take you to the next level. Use the tech stack your comfortable with to accomplish your goal - be it dev or just to "take it for a spin (with or without some bells and whistles)". 

Given that this repo started pre-rpm, maybe it's OK for it to shift it's purpose.

I'd suggest a directory structure like this.  The landing page README can say not only how to navigate them, but also why each one would exist and what they're general use cases for them are - I think that's the bit we're lacking.  Then the sub-directories can have their own READMEs with sufficient levels of detail.
`<top level by tech>/<next level by functionality provided>`
```
vm/
vagrant/
vagrant/ood
vagrant/ood-with-slurm
vagrant/ood-with-pbspro
container/
```

**Comment by treydock** [comment]
I'd change `container` to be `docker` and whatever other technologies we'll support like singularity.

**Comment by ericfranz** [comment]
If we move to this, I can still get a single subdirectory using GitHub's subversion support:

```
➜  vms svn export https://github.com/osc/ood-images/trunk/containers/podman podman
A    podman
A    podman/README.md
A    podman/bashrc
A    podman/env
A    podman/launch-httpd
A    podman/make-dev-img.sh
A    podman/make-ood-base-img.sh
A    podman/make-personal-img.sh
A    podman/ood-container
Exported revision 43.
➜  vms ls -1 podman
.
..
README.md
bashrc
env
launch-httpd
make-dev-img.sh
make-ood-base-img.sh
make-personal-img.sh
ood-container
```

Yeah, we should rename `container` to be `docker` and instead of `container/podman` rename those to `podman/ood` to clarify what the image is (that it isn't `podman/ood_with_slurm` and we can still add that later if we would like).

Will there be anyone outside of OSC who have cloned this repo that will be surprised when we make this change? Also, maybe @MorganRodgers could chime in on any ramifications related to SGCI. I don't recall what he did with them and OOD for making images available.

**Comment by johrstrom** [comment]
Not quite sure why this got closed with the PR, maybe because it was mentioned in the very first comment.

Either way, the directory structure we have now sets us up to include ood-images-full if we want. However, I now see that I am unable to carry that initiative forward is exclusively vagrant images which I don't use.
